train:
    hyparam_file: ./config/resnet18.yml
    optional_file: ./config/resnet18.yml
    label2id_file: ./train_data/label_to_id_train.txt
    id2name_file: ./train_data/label_map.json
    output_model_name: last.pth
    hyparam_file_custom: ./config/resnet18.yml
eval:
    hyparam_file: ./config/resnet18.yml
    optional_file: ./config/resnet18.yml
    batch_size: 8
    num_worker: 4
    hyparam_file_custom: ./config/resnet18.yml
to_onnx:
    hyparam_file: ./config/resnet18.yml
    optional_file: ./config/resnet18.yml
    hyparam_file_custom: ./config/resnet18.yml
demo:
    hyparam_file: ./config/resnet18.yml
    optional_file: ./config/resnet18.yml
    hyparam_file_custom: ./config/resnet18.yml
     
    
    
